services:
  backend1:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend1
    environment:
      - SERVICE_NAME=backend-1
      - PORT=8081
      - LATENCY_JITTER_MS=100
    expose:
      - "8081"

  backend2:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend2
    environment:
      - SERVICE_NAME=backend-2
      - PORT=8081
      - LATENCY_JITTER_MS=100
    expose:
      - "8081"

  backend3:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend3
    environment:
      - SERVICE_NAME=backend-3
      - PORT=8081
      - LATENCY_JITTER_MS=100
    expose:
      - "8081"

  lb:
    build:
      context: ./lb
      dockerfile: Dockerfile
    container_name: lb
    environment:
      - PORT=8080
      - BACKENDS=http://backend1:8081,http://backend2:8081,http://backend3:8081
    ports:
      - "8080:8080"
    depends_on:
      - backend1
      - backend2
      - backend3
  prometheus:
    image: prom/prometheus:v2.55.1
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    depends_on:
      - lb
      - backend1
      - backend2
      - backend3
      - benchctl

  grafana:
    image: grafana/grafana:11.2.0
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus

  benchctl:
    build: ./benchctl
    container_name: benchctl
    ports:
      - "7070:7070"
    depends_on:
      - lb

  wrk:
    image: williamyeh/wrk
    container_name: wrk
    entrypoint: ["sleep", "infinity"]
