global:
  scrape_interval: 2s
  evaluation_interval: 2s

scrape_configs:
  - job_name: "lb"
    static_configs:
      - targets: ["lb:8080"]
        labels: { group: "edge" }

  - job_name: "backends"
    static_configs:
      - targets: ["backend1:8081", "backend2:8081", "backend3:8081"]
        labels: { group: "app" }

  - job_name: "benchctl"
    static_configs:
      - targets: ["benchctl:7070"]
        labels: { group: "bench" }
