version: "3.8"

services:
  backend1:
    image: nginx:alpine
    container_name: backend1
    volumes:
      - ./backend1/index.html:/usr/share/nginx/html/index.html
    ports:
      - "8081:80"
    networks:
      - lbnet

  backend2:
    image: nginx:alpine
    container_name: backend2
    volumes:
      - ./backend2/index.html:/usr/share/nginx/html/index.html
    ports:
      - "8082:80"
    networks:
      - lbnet

  wrk:
    image: williamyeh/wrk
    container_name: loadtester
    entrypoint: ["tail", "-f", "/dev/null"]
    networks:
      - lbnet

networks:
  lbnet:
    driver: bridge
